// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeKejAiQ4J7moCA-caCB2FxV4yJdRbC0E',
    appId: '1:756276095403:web:c694db5d67811153dc0aee',
    messagingSenderId: '756276095403',
    projectId: 'hhstudios-4ce70',
    authDomain: 'hhstudios-4ce70.firebaseapp.com',
    databaseURL: 'https://hhstudios-4ce70.firebaseio.com',
    storageBucket: 'hhstudios-4ce70.appspot.com',
    measurementId: 'G-TL6KY81T32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6PciQaX5CmCGNYRzupKr47T59U2h4Y44',
    appId: '1:756276095403:android:5a3a1792f318bc24dc0aee',
    messagingSenderId: '756276095403',
    projectId: 'hhstudios-4ce70',
    databaseURL: 'https://hhstudios-4ce70.firebaseio.com',
    storageBucket: 'hhstudios-4ce70.appspot.com',
  );
}
